### ISSUE TITLE
Validade accessToken / Fetch user when logged in

### ISSUE THREAD

**Issue by SouzaGabriel26** [SouzaGabriel26/onde-ir#51]
## Tasks
- [x] Validate accessToken integrity when user signIn
- [x] Fetch user with the `id` in accessToken
- [x] If one of the above steps fail, logout user
