### ISSUE TITLE
[`models/place`]: Improve `findAll` method

### ISSUE THREAD

**Issue by SouzaGabriel26** [SouzaGabriel26/onde-ir#75]
## Tasks
- [x] Add support to return `place_images`
- [x] Add support to return `place_likes`
- [x] Add support to return `place_comments`
