### ISSUE TITLE
Create script to populate tables

### ISSUE THREAD

**Issue by SouzaGabriel26** [SouzaGabriel26/onde-ir#8]
## Tasks:
- [x]  script to populate `users` table
- [x] script to populate `restaurants` table
- [x] script to populate `restaurant_likes` table
- [x] script to populate `restaurant_images` table
- [x] script to populate `restaurant_comments` table
